pref("extensions.marginalvoice.transcriptionMode", "python");
pref("extensions.marginalvoice.pythonPath", "");
pref("extensions.marginalvoice.helperScriptPath", "");
pref("extensions.marginalvoice.customCommandPath", "");
pref("extensions.marginalvoice.customCommandArgs", "");
pref("extensions.marginalvoice.whisperModel", "base");
pref("extensions.marginalvoice.triggers", '[{"phrase":"quote","color":"#ffd400"},{"phrase":"Main Theory","color":"#2ea8e5"},{"phrase":"Key Point","color":"#ff6666"},{"phrase":"Definition","color":"#5fb236"}]');
pref("extensions.marginalvoice.fuzzyThreshold", "0.6");
pref("extensions.marginalvoice.silenceTimeout", 5);
pref("extensions.marginalvoice.skipDuplicates", true);
pref("extensions.marginalvoice.logLevel", "info");
pref("extensions.marginalvoice.liveMode", "toggle");
pref("extensions.marginalvoice.liveShortcut", "CmdOrCtrl+Shift+V");
pref("extensions.marginalvoice.liveShowOverlay", true);
pref("extensions.marginalvoice.liveFlushInterval", 2);
pref("extensions.marginalvoice.liveOverlayPos", "");